name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  mix_test:
    name: mix test (Elixir ${{matrix.pair.elixir}} | Erlang/OTP ${{matrix.pair.otp}})
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: 1.14.1
              otp: 25.1.2
          - pair:
              elixir: 1.12.3
              otp: 24.0.6
          - pair:
              elixir: 1.7.4
              otp: 19.3.6
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - name: Run PostgreSQL 11
        run: |
          docker run --env POSTGRES_USER=postgres \
            --env POSTGRES_DB=ecto_psql_extras_test \
            --env POSTGRES_PASSWORD=postgres \
            -d -p 5432:5432 postgres:11.5-alpine \
            postgres -c shared_preload_libraries=pg_stat_statements
          sleep 2
      - name: Run PostgreSQL 12
        run: |
          docker run --env POSTGRES_USER=postgres \
            --env POSTGRES_DB=ecto_psql_extras_test \
            --env POSTGRES_PASSWORD=postgres \
            -d -p 5433:5432 postgres:12.7-alpine \
            postgres -c shared_preload_libraries=pg_stat_statements
          sleep 2
      - name: Run PostgreSQL 13
        run: |
          docker run --env POSTGRES_USER=postgres \
            --env POSTGRES_DB=ecto_psql_extras_test \
            --env POSTGRES_PASSWORD=postgres \
            -d -p 5434:5432 postgres:13.3-alpine \
            postgres -c shared_preload_libraries=pg_stat_statements
          sleep 5
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only test
      - name: Run tests for PG 11
        env:
          PG_VERSION: 11
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_DB: ecto_psql_extras_test
          POSTGRES_PASSWORD: postgres
        run: |
          sleep 4 # wait pg
          mix test --include distribution
      - name: Run tests for PG 12
        env:
          PG_VERSION: 12
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_DB: ecto_psql_extras_test
          POSTGRES_PASSWORD: postgres
        run: |
          sleep 4 # wait pg
          mix test --include distribution
      - name: Run tests for PG 13
        env:
          PG_VERSION: 13
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_DB: ecto_psql_extras_test
          POSTGRES_PASSWORD: postgres
        run: |
          sleep 4 # wait pg
          mix test --include distribution
